# Generated by Django 3.2.3 on 2021-06-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_question_id_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_true',
        ),
        migrations.AddField(
            model_name='answer',
            name='right_answer',
            field=models.BooleanField(default=1, verbose_name='Right Answer'),
            preserve_default=False,
        ),
    ]
