# Generated by Django 3.2.3 on 2021-06-02 07:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_userscores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserScores',
            new_name='UserPoint',
        ),
    ]
