# Generated by Django 3.2.3 on 2021-06-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_userscores_userpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='right_answer',
            new_name='is_true',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
    ]
